language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.3"
services:
  - postgresql
test:
   adapter: postgresql
   database: todo
   username: test
   password: test
before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test';"
  - psql -c 'create database todo;' -U postgres
  - psql -c 'grant all privileges on database todo to test;' -U postgres