language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.3"
services:
  - postgresql
test:
   adapter: postgresql
   database: todo
   username: test
   password: test
before_script:
  - psql -c "CREATE USER sylvain WITH PASSWORD 'sylvain';"
  - psql -c 'create database tests;' -U postgres
  - psql -c 'grant all privileges on database tests to sylvain;' -U postgres
after_success:
- mvn cobertura:cobertura coveralls:report